services:
  db:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: my-todo-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Username=postgres;Password=1234;Database=todo_db
    depends_on:
      - db

  dashboard:
    build:
      context: ../TodoDashboard
    container_name: my-dashboard
    ports:
      - "5005:8080"
    depends_on:
      - api

volumes:
  pgdata: